#!/usr/bin/env python3
"""src/ds41/cuda/dense_golden/gen_rope_golden.py - DS1-B: the golden values of the RoPE table, from the numpy oracle.

    python3 src/ds41/cuda/dense_golden/gen_rope_golden.py > src/ds41/cuda/dense_rope_golden.inc

Writes `kRopeGolden`, a table of {plain, pos, pair, cos bits, sin bits} entries of ref/ds41/rope.py: rope_table(dim = 64, ...) in float64 and cast to float32 (what the
device table holds), for the two parameter sets of the model (docs/deepseek/RESEARCH.md section 1: layers 0-1 theta 10000 without YaRN; all other layers theta 160000
with YaRN factor 16, beta_fast 32, beta_slow 1, original_seq_len 65536).  src/ds41/cuda/dense_emu_test.cpp (--rope) compares the host table builder
ds41_rope_table_host with it to within 1 ulp.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", ".."))
from ref.ds41.rope import rope_table  # noqa: E402

SEQ = 70000
POSITIONS = [0, 1, 2, 3, 7, 31, 100, 511, 1000, 4095, 8191, 20000, 65535, 65536, 69999]
PAIRS = [0, 1, 2, 5, 9, 13, 14, 15, 16, 20, 25, 30, 31]


def main():
    sets = [(1, rope_table(64, SEQ, 0, 10000.0, 16.0, 32.0, 1.0)), (0, rope_table(64, SEQ, 65536, 160000.0, 16.0, 32.0, 1.0))]
    print("// generated by src/ds41/cuda/dense_golden/gen_rope_golden.py from ref/ds41/rope.py (float64, cast to float32): do not edit")
    print("struct RopeGoldenEntry {\n    int plain;        // 1: theta 10000, no YaRN; 0: theta 160000 + YaRN (original_seq_len 65536)\n    int pos, pair;\n    uint32_t cos, sin;   // float32 bits\n};")
    print("static const RopeGoldenEntry kRopeGolden[] = {")
    for plain, (c, s) in sets:
        c32, s32 = c.astype(np.float32), s.astype(np.float32)
        for p in POSITIONS:
            for i in PAIRS:
                print("    {%d, %d, %d, 0x%08Xu, 0x%08Xu}," % (plain, p, i, int(c32[p, i].view(np.uint32)), int(s32[p, i].view(np.uint32))))
    print("};")


if __name__ == "__main__":
    main()
